### ISSUE TITLE
Strange please

### ISSUE THREAD

**Issue by f0rmat1k** [junosuarez/projector#1]
Hello. It's really strange please, but ...
Could you give me `creator` repository in the NPM? I gonna write CLI tool, that will help to create files structure in your projects (extended my [Bemy](http://github.com/f0rmat1k/bemy) tool). And i saw, that you didn't update your repo for 3 years and your tool [has not so much downloads for last half of year](http://npm-stat.com/charts.html?package=projector&author=&from=2016-01-09&to=2016-07-09). So i thought, maybe you could give it to me.

**Comment by junosuarez** [comment]
Hi, thanks for opening an issue. I'm not sure what you mean by 

> Could you give me `creator` repository in the NPM?

Could you please clarify?

**Comment by f0rmat1k** [comment]
I'm meaning repository owner. (Npm owner add f0rmat1k). Of course only If you dont need this repo anymore. I ask, because this repo name very suitable for my CLI tool.

**Comment by junosuarez** [comment]
I understand now. Unfortunately, I would like to retain ownership of the `projector` package on npm. Best of luck with your package!
